name: 'Build for Linux'
inputs:
  name: # vlc-rpc-v${{steps.get-version.outputs.version}}-nightly${{env.NOW}}-bundled-linux-x64
    required: true
runs:
  using: "composite"
  steps:
    - name: Package for Linux
      run: |
        mkdir -p .dist/zipped/
        mkdir -p .dist/linux-x64/
        mkdir -p .help/linux-x64/node
        cp -rv * .dist/linux-x64/
        archiveName=$(wget -O - https://nodejs.org/download/release/latest/ | grep -Poh "node-v[0-9]+.[0-9]+.[0-9]+-linux-x64.tar.gz(?=<)")
        wget -P .help/linux-x64 "https://nodejs.org/download/release/latest/$archiveName"
        tar -zxvf ".help/linux-x64/$archiveName" -C .help/linux-x64/node
        cp -rv .help/linux-x64/node/**/bin/node .dist/linux-x64/
        zip -r ".dist/zipped/${{inputs.name}}.zip" .dist/linux-x64
      shell: bash
    - name: Archive Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{inputs.name}}
        path: |
          .dist/linux-x64
