name: Release

on: 
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Get current date
        id: get-date
        run: |
          echo "NOW=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
          
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
          
      - name: Get Version From package.json
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .
          
      - uses: ./.github/actions/nodeci-build-windows
        with:
          name: vlc-rpc-v${{steps.get-version.outputs.version}}-bundled-win-x64
          
      - uses: ./.github/actions/nodeci-build-linux
        with:
          name: vlc-rpc-v${{steps.get-version.outputs.version}}-bundled-linux-x64
          
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vlc-rpc-v${{steps.get-version.outputs.version}}-bundled-win-x64
          path: |
            .dist/win-x64

      - name: Upload Artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: build-artifact
          retention-days: 30
          if-no-files-found: error
          path: .dist/zipped/*.zip

      - name: Upload to Release
        id: release
        if: ${{ github.event_name == 'release' }}
        uses: shogo82148/actions-upload-release-asset@dccd6d23e64fd6a746dce6814c0bde0a04886085 # v1.7.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          overwrite: true
          asset_path: .dist/zipped/*.zip
